[package]
name = "imagen"
version = "0.2.0"
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
rayon = "1.3"
structopt = "0.3"

[dependencies.image]
version = "0.21"
default-features = false
features = ["jpeg"]
